# Generated by Django 2.0.1 on 2018-01-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisjobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gisjob',
            options={'verbose_name': 'GIS Job'},
        ),
        migrations.AlterModelOptions(
            name='gispro',
            options={'verbose_name': 'GIS Person'},
        ),
        migrations.AlterModelOptions(
            name='jobsubmitter',
            options={'verbose_name': 'Job Request Submitter'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Office'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Internal Project'},
        ),
        migrations.AlterField(
            model_name='gisjob',
            name='date_assigned',
            field=models.DateTimeField(blank=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='gisjob',
            name='project_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gisjobs.Project'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_add1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_add2',
            field=models.CharField(blank=True, max_length=24, verbose_name='Ste'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='ZIP'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
