# Generated by Django 2.0.1 on 2018-01-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisjobs', '0003_auto_20180123_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisjob',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
