# Generated by Django 2.0.1 on 2018-01-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisjobs', '0006_auto_20180122_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisjob',
            name='date_assigned',
            field=models.DateTimeField(null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='gisjob',
            name='date_completed',
            field=models.DateTimeField(null=True, verbose_name='Completed'),
        ),
    ]
