# Generated by Django 2.0.1 on 2018-01-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisjobs', '0007_auto_20180122_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisjob',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gisjobs.GISpro'),
        ),
    ]
