# Generated by Django 2.0.1 on 2018-01-24 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisjobs', '0008_auto_20180122_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmitter',
            name='employee_office',
        ),
        migrations.AlterField(
            model_name='gisjob',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gisjob',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GISpro',
        ),
        migrations.DeleteModel(
            name='JobSubmitter',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
