# Generated by Django 2.0.1 on 2018-01-24 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisjobs', '0011_auto_20180124_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisjob',
            name='submitted_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
