# Generated by Django 2.0.1 on 2018-01-24 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gisjobs', '0012_auto_20180124_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisjob',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='gisjob',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
